### ISSUE TITLE
Site not correctly deployed to s3

### ISSUE THREAD

**Issue by danielfdsilva** [openaq/openaq-metadata-editor#48]
S3 by default does not work with SPAs. When an url is loaded it interprets the path segments as folders and throws an error because the file was not found.
Ex: https://metadata.openaq-staging.org/location/AE-2

This is fixable by redirecting the requests to the index document. Here's a [guide](https://medium.com/@P_Lessing/single-page-apps-on-aws-part-1-hosting-a-website-on-s3-3c9871f126) that may help.

**Comment by danielfdsilva** [comment]
cc @jflasher

**Comment by olafveerman** [comment]
@jflasher I think this has to be set up through the interface. Let us know if this is something we can solve on our end.

**Comment by sethvincent** [comment]
I think all we need is to set a custom error response in the cloudformation distribution, for example:

```
CustomErrorResponses:
  - ErrorCode: 404
    ResponseCode: 200
    ResponsePagePath: /index.html
```
